import type { Dashboard } from "@pont/shared";

export function mockDashboard(): Dashboard {
  return {
    source: "mock",
    capturedAt: new Date().toISOString(),
    student: {
      id: "1",
      name: "Mar Serra i Puig",
      course: "3r ESO B",
      center: "IES Exemple",
    },
    students: [
      {
        id: "1",
        name: "Mar Serra i Puig",
        course: "3r ESO B",
        center: "IES Exemple",
        group: "3r ESO B",
        tutorName: "Anna Tutor",
      },
      {
        id: "2",
        name: "Nil Serra i Puig",
        course: "5é Primària",
        center: "CEIP Exemple",
        group: "5é A",
        tutorName: "Joan Tutor",
      },
    ],
    notices: [
      {
        id: "n1",
        title: "Reunió de tutors (Mar)",
        body: "Dimarts 17:30. Porta l'agenda si pots.",
        date: "2026-03-10",
        author: "Tutor/a",
        unread: true,
        studentId: "1",
        studentName: "Mar Serra i Puig",
      },
      {
        id: "n2",
        title: "Sortida cultural (Mar)",
        body: "Autorització pendent per al museu.",
        date: "2026-03-08",
        author: "Cap d'estudis",
        studentId: "1",
        studentName: "Mar Serra i Puig",
      },
      {
        id: "n3",
        title: "Menú menjador (Nil)",
        body: "Menú del mes de març adjunt.",
        date: "2026-03-01",
        author: "Menjador",
        studentId: "2",
        studentName: "Nil Serra i Puig",
      },
    ],
    absences: [
      {
        id: "a1",
        date: "2026-03-09",
        subject: "Matemàtiques",
        kind: "retard",
        justified: false,
        comment: "5 minuts",
        studentId: "1",
        studentName: "Mar Serra i Puig",
      },
      {
        id: "a2",
        date: "2026-03-02",
        subject: "Educació Física",
        kind: "falta",
        justified: true,
        comment: "Visita mèdica",
        studentId: "1",
        studentName: "Mar Serra i Puig",
      },
      {
        id: "a3",
        date: "2026-03-05",
        subject: "Coneixement del medi",
        kind: "falta",
        justified: true,
        studentId: "2",
        studentName: "Nil Serra i Puig",
      },
    ],
    grades: [
      {
        id: "g1",
        subject: "Valencià",
        evaluation: "2a avaluació",
        value: "8",
        comment: "Bona expressió oral",
        studentId: "1",
        studentName: "Mar Serra i Puig",
      },
      {
        id: "g2",
        subject: "Matemàtiques",
        evaluation: "2a avaluació",
        value: "7",
        studentId: "1",
        studentName: "Mar Serra i Puig",
      },
      {
        id: "g3",
        subject: "Anglès",
        evaluation: "2a avaluació",
        value: "9",
        studentId: "1",
        studentName: "Mar Serra i Puig",
      },
      {
        id: "g4",
        subject: "Matemàtiques",
        evaluation: "1a avaluació",
        value: "9",
        studentId: "2",
        studentName: "Nil Serra i Puig",
      },
    ],
    messages: [
      {
        id: "m1",
        subject: "Treball de sintet",
        from: "Departament de Ciències",
        date: "2026-03-07",
        preview: "Recordeu lliurar el dossier abans de divendres.",
        unread: true,
        studentId: "1",
        studentName: "Mar Serra i Puig",
      },
      {
        id: "m2",
        subject: "Excursió al parc",
        from: "Tutor/a",
        date: "2026-03-04",
        preview: "Cal autorització firmada.",
        studentId: "2",
        studentName: "Nil Serra i Puig",
      },
    ],
    activities: [
      {
        id: "act1",
        title: "Jornada de portes obertes",
        date: "2026-03-21",
        place: "Pavelló",
        description: "Horari 10:00–13:00",
        studentId: "1",
        studentName: "Mar Serra i Puig",
      },
      {
        id: "act2",
        title: "Teatre escolar",
        date: "2026-03-18",
        place: "Sala d'actes",
        studentId: "2",
        studentName: "Nil Serra i Puig",
      },
    ],
    behaviors: [
      {
        id: "b1",
        date: "2026-02-28",
        subject: "Tutoria",
        description: "Col·laboració a l'aula",
        kind: "positiu",
        studentId: "1",
        studentName: "Mar Serra i Puig",
      },
    ],
    subjects: [
      {
        id: "s1",
        subject: "Matemàtiques",
        teacher: "Tutor/a Exemple",
        attention: "Dijous, de 13:00 a 15:00 h.",
        studentId: "1",
        studentName: "Mar Serra i Puig",
      },
      {
        id: "s2",
        subject: "Valencià",
        teacher: "Tutor/a Exemple",
        attention: "Dijous, de 13:00 a 15:00 h.",
        studentId: "1",
        studentName: "Mar Serra i Puig",
      },
      {
        id: "s3",
        subject: "Coneixement del medi",
        teacher: "Joan Tutor",
        attention: "Dimecres 12:00",
        studentId: "2",
        studentName: "Nil Serra i Puig",
      },
    ],
    schedule: [
      {
        id: "h1",
        day: "Dilluns",
        start: "09:00",
        end: "09:40",
        subject: "Matemàtiques",
        studentId: "1",
        studentName: "Mar Serra i Puig",
      },
      {
        id: "h2",
        day: "Dilluns",
        start: "09:40",
        end: "10:20",
        subject: "Valencià",
        studentId: "1",
        studentName: "Mar Serra i Puig",
      },
      {
        id: "h3",
        day: "Dimarts",
        start: "09:00",
        end: "09:40",
        subject: "Educació Física",
        studentId: "1",
        studentName: "Mar Serra i Puig",
      },
      {
        id: "h4",
        day: "Dilluns",
        start: "09:00",
        end: "10:00",
        subject: "Llengua",
        studentId: "2",
        studentName: "Nil Serra i Puig",
      },
      {
        id: "h5",
        day: "Dilluns",
        start: "10:00",
        end: "11:00",
        subject: "Matemàtiques",
        studentId: "2",
        studentName: "Nil Serra i Puig",
      },
      {
        id: "h6",
        day: "Dimecres",
        start: "09:00",
        end: "10:00",
        subject: "Educació Artística",
        studentId: "2",
        studentName: "Nil Serra i Puig",
      },
    ],
    attachments: [],
    menus: [
      {
        sourceFile: "menu_exemple_mar.pdf",
        centerName: "IES Exemple",
        year: 2026,
        month: 3,
        attachmentId: undefined,
        studentId: "1",
        studentName: "Mar Serra i Puig",
        variants: [
          {
            name: "General",
            days: [
              {
                date: "2026-03-10",
                dayOfMonth: 10,
                weekday: "Dimarts",
                courses: ["Llenties", "Pollastre al forn", "Amanida"],
                saladCode: "A",
                dessert: "Iogurt",
                nutrition: { kcal: 720 },
              },
              {
                date: "2026-03-11",
                dayOfMonth: 11,
                weekday: "Dimecres",
                courses: ["Sopa de verdura", "Truita", "Pa"],
                saladCode: "B",
                dessert: "Poma",
                nutrition: { kcal: 680 },
              },
            ],
          },
        ],
      },
      {
        sourceFile: "menu_exemple_nil.pdf",
        centerName: "CEIP Exemple",
        year: 2026,
        month: 3,
        studentId: "2",
        studentName: "Nil Serra i Puig",
        variants: [
          {
            name: "General",
            days: [
              {
                date: "2026-03-10",
                dayOfMonth: 10,
                weekday: "Dimarts",
                courses: ["Arròs", "Peix", "Amanida"],
                saladCode: "C",
                dessert: "Fruita",
                nutrition: { kcal: 650 },
              },
            ],
          },
        ],
      },
    ],
    diagnostics: {
      pages: [],
      navLinks: [],
      scrapedStudents: [
        { id: "1", name: "Mar Serra i Puig", notices: 2, schedule: 3, subjects: 2, absences: 2, menus: 1, tutorName: "Anna Tutor", group: "3r ESO B" },
        { id: "2", name: "Nil Serra i Puig", notices: 1, schedule: 3, subjects: 1, absences: 1, menus: 1, tutorName: "Joan Tutor", group: "5é A" },
      ],
    },
  };
}
